### ISSUE TITLE
More languages? (Catallan)

### ISSUE THREAD

**Issue by jaumet** [stanford-oval/WikiChat#35]
Hi there!
I'm fascinated about wikichat.
Maybe you know it, Catalan, my language, used to have an overrated size as a wikipedia according to number of speakers, in relation to the rest of top languages.
Yes, Catalans like languages :-)

Is there a how-to on how to implement a new language?
I'd voluntary to , add Catalan. And many other languages will come u, reflecting wikipediam anf ree software way.

It is existing already?
Would it be that possible?

Many thanks
Jaume

**Comment by s-jse** [comment]
Hi,

Thank you for your interest in WikiChat. Support for a new language in WikiChat comes from two sources:
1. The multilingual capability of the underlying large language model (e.g. GPT-4o). This enables WikiChat to understand different languages and respond to users in the language they prefer. This is most likely already supported in WikiChat.

1. Access to Wikipedia data in a new language, for example data from https://ca.wikipedia.org/. This requires "indexing" the Wikipedia for the new language, and adding that to the index that WikiChat is already using. But this needs to be done by us, because it needs to be hosted on our server for everyone to access it.

You can try the first one by asking WikiChat something in Catalan. Let us know if you run into any issues with this.
I might get around to running the second one in the future.

**Comment by s-jse** [comment]
We've added support for the Catalan Wikipedia. Could you please give it a try and tell us if it is working correctly? Thank you!
