### ISSUE TITLE
These seven steps are not deterministic at each step, is it about alleviating hallucination rather than eliminating it?

### ISSUE THREAD

**Issue by yuedajiong** [stanford-oval/WikiChat#5]
human-level?

**Comment by s-jse** [comment]
Hi,

I'm not sure if I fully understand your question. All steps in WikiChat _are_ deterministic, for instance, all temperature values are set to 0 by default (i.e. greedy decoding).
You may see slightly different results with OpenAI due to the fact that its outputs are not fully deterministic even with greedy decoding (See the numerous posts about this topic on the OpenAI community forum, for example [this](https://community.openai.com/t/run-same-query-many-times-different-results/140588/10)).

Also, please note that asking the same question with different conversation histories might also result in different outputs, since previous conversation turns are also part of the input given to the LLM. For example, the following two conversations may have slightly different outputs:

> User: Hi
> WikiChat: Hi, how can I help you?
> User: Tell me about Haruki Murakami.

> User: Tell me about Haruki Murakami.


Regarding alleviating vs eliminating hallucination, WikiChat achieves 97.3% factual accuracy on average when tested with `gpt-4` as the underlying LLM. This test includes conversations on challenging "recent" or "tail" topics.
If weaker LLMs are used as WikiChat's backbone, the hallucination slightly increases. For example, with `text-davinci-003`, factual accuracy is 89.2%. Please refer to [our paper](https://aclanthology.org/2023.findings-emnlp.157/) for more numbers and details.

**Comment by yuedajiong** [comment]
Thanks
